version: '0.1'
services:
  uploader:
    image: docker.breakout.xyz:5000/media-uploader:latest
    ports:
    - "3001:3001"
    volumes:
    - media:/media
  uploader:
    image: docker.breakout.xyz:5000/media-recoder:latest
    volumes:
    - media:/media